/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Timer 2 blink LED at 100ms
 ******************************************************************************
 */

#include <stm32f401xe.h>

#define TIM2ENR			(1U<<0)

int main(void)
{
	//1. Setup a Clock for TIM-2 and GPIOA
	RCC -> AHB1ENR |= (1U<<0); // GPIOA is Enabled
	RCC -> APB1ENR |= TIM2ENR;

	//2. Setup the Mode Register for GPIOA PA0
	GPIOA -> MODER |= (1U<<0);// output mode

	//3. TIM2 Setup for CR1
	TIM2 -> CR1 = 0;

	//4. TIM2 Setup the CCMR register
	//TIM2 -> CCMR1 |= (1U<<5)|(1U<<4);

	//5. TIM2 clear previous counter values
	TIM2 -> CNT = 0;

	//6. TIM2 Setup for Prescale
	TIM2 -> PSC = 1600 - 1;// 1599

	//7. TIM2 Setup for Auto Reload Register
	TIM2 -> ARR = 500;

	//8. TIM2 Enable the Register to generate waveforms
	TIM2 -> CR1 |= (1U<<0);

	while(1)
	{
		while((TIM2 -> SR & (1U<<0))==0)
		{}
		GPIOA -> ODR ^= (1U<<0);
	}
}
